CREATE TABLE Student (
    Id          INT PRIMARY KEY AUTO_INCREMENT,
    Name        VARCHAR(255) NOT NULL,
    Surname     VARCHAR(255) NOT NULL,
    MobilePhone VARCHAR(15),
    Age         INT,
    Email       VARCHAR(255) UNIQUE,
    CreatedAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)